MVCMovie/Models/Movie.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Web.Helpers;
using Newtonsoft.Json;

namespace MVCMovie.Models
{
    public class Movie
    {
        public int ID { get; set; }

        [StringLength(60, MinimumLength = 3)]
        [Required]
        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

        [Display(Name = "Release Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime ReleaseDate { get; set; }

        [RegularExpression(@"^[A-Z]+[a-zA-Z'\s]*$")]
        [Required]
        [StringLength(30)]
        public string Genre { get; set; }

        [Range(1, 100)]
        [DataType(DataType.Currency)]
        [Required]
        public decimal Price { get; set; }

        [RegularExpression(@"^[A-Z]+[a-zA-Z'\s]*$")]
        [StringLength(5)]
        [Required]
        public string Rating { get; set; }
    }

    public class MovieDBContext : DbContext
    {
        public DbSet<Movie> Movies { get; set; }
    }
}

MVCMovie/Controllers/HelloWorldController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCMovie.Controllers
{
    public class HelloWorldController : Controller
    {
        //
        // GET: /HelloWorld/5

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /HelloWorld/Welcome/
        public ActionResult Welcome(string name, int numTimes = 1)
        {
            ViewBag.Message = "Hello " + name;
            ViewBag.NumTimes = numTimes;
            return View();
        }
    }
}

MVCMovie/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCMovie.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVCMovie/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCMovie.Helper;
using MVCMovie.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json.Serialization;

namespace MVCMovie.Controllers
{
  public class MoviesController : Controller
  {
    private MovieDBContext db = new MovieDBContext();

    // GET: Movies
    public ActionResult Index(string movieGenre, string searchString)
    {
      var GenreLst = new List<string>();

      var GenreQry = from d in db.Movies
        orderby d.Genre
        select d.Genre;


      GenreLst.AddRange(GenreQry.Distinct());
      ViewBag.movieGenre = new SelectList(GenreLst);

      var movies = from m in db.Movies
        select m;

      if (!String.IsNullOrEmpty(searchString))
      {
        movies = movies.Where(s => s.Title.Contains(searchString));
      }

      if (!String.IsNullOrEmpty(movieGenre))
      {
        movies = movies.Where(x => x.Genre == movieGenre);
      }

      return View(movies);
    }

    public string GetMovieListJson()
    {
      var MovieJsonList = from m in db.Movies
        select m;

      return JsonConvert.SerializeObject(MovieJsonList, new JsonHelper().serializerSettings);
    }

    // GET: Movies/Details/5
    public ActionResult Details(int? id)
    {
      if (id == null)
      {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }

      Movie movie = db.Movies.Find(id);
      if (movie == null)
      {
        return HttpNotFound();
      }

      return View(movie);
    }

    // GET: Movies/Create
    public ActionResult Create()
    {
      return View();
    }

    // POST: Movies/Create
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for
    // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    /*[ValidateAntiForgeryToken]*/
    public ActionResult Create(Movie movie)
    {
      if (ModelState.IsValid)
      {

        db.Movies.Add(movie);
        db.SaveChanges();
        Console.WriteLine("Added Movie: " + movie.Title);
        return RedirectToAction("Index");
      }
      Console.WriteLine("Failed");


      return View(movie);
    }

    // GET: Movies/Edit/5
    public ActionResult Edit(int? id)
    {
      if (id == null)
      {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }

      Movie movie = db.Movies.Find(id);
      if (movie == null)
      {
        return HttpNotFound();
      }

      return View(movie);
    }

    // POST: Movies/Edit/5
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for
    // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit([Bind(Include = "ID,Title,ReleaseDate,Genre,Price,Rating")]
      Movie movie)
    {
      if (ModelState.IsValid)
      {
        db.Entry(movie).State = EntityState.Modified;
        db.SaveChanges();
        return RedirectToAction("Index");
      }

      return View(movie);
    }

    // GET: Movies/Delete/5
    public ActionResult Delete(int? id)
    {
      if (id == null)
      {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }

      Movie movie = db.Movies.Find(id);
      if (movie == null)
      {
        return HttpNotFound();
      }

      return View(movie);
    }

    // POST: Movies/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public ActionResult DeleteConfirmed(int id)
    {
      Movie movie = db.Movies.Find(id);
      db.Movies.Remove(movie);
      db.SaveChanges();
      return RedirectToAction("Index");
    }


    protected override void Dispose(bool disposing)
    {
      if (disposing)
      {
        db.Dispose();
      }

      base.Dispose(disposing);
    }
  }
}

MVCMovie/Views/HelloWorld/Index.cshtml
@{
    ViewBag.Title = "Movie List";
}

<h2>My Movie List</h2>
<p>Hello World from the View Template!</p>

MVCMovie/Views/HelloWorld/Welcome.cshtml
@{ 
    ViewBag.Title = "Welcome";
}

<h2>Welcome</h2>

<ul>
    @for (int i = 0; i < ViewBag.numTimes; i++)
    {
        <li>@ViewBag.Message</li>
    }
</ul>

MVCMovie/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVCMovie/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVCMovie/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="content">
  <h3 class="content__title">
    Welcome to the worst movie website!
  </h3>
</div>

MVCMovie/Views/Movies/Create.cshtml
@model MVCMovie.Models.Movie

@{
  ViewBag.Title = "Create";
}

<h2>Create</h2>

<div class="create-movie__react-anchor"></div>
<div>
  @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
  @Scripts.Render("~/bundles/jqueryval")
}

MVCMovie/Views/Movies/Delete.cshtml
@model MVCMovie.Models.Movie

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
  <h4>Movie</h4>
  <hr />
  <dl class="data-list">
    <dt class="data-list__terms">
      @Html.DisplayNameFor(model => model.Title)
    </dt>

    <dd class="data-list__description">
      @Html.DisplayFor(model => model.Title)
    </dd>

    <dt class="data-list__terms">
      @Html.DisplayNameFor(model => model.ReleaseDate)
    </dt>

    <dd class="data-list__description">
      @Html.DisplayFor(model => model.ReleaseDate)
    </dd>

    <dt class="data-list__terms">
      @Html.DisplayNameFor(model => model.Genre)
    </dt>

    <dd class="data-list__description">
      @Html.DisplayFor(model => model.Genre)
    </dd>

    <dt class="data-list__terms">
      @Html.DisplayNameFor(model => model.Price)
    </dt>

    <dd class="data-list__description">
      @Html.DisplayFor(model => model.Price)
    </dd>

    <dt class="data-list__terms">
      @Html.DisplayNameFor(model => model.Rating)
    </dt>

    <dd class="data-list__description">
      @Html.DisplayFor(model => model.Rating)
    </dd>
  </dl>

  @using (Html.BeginForm())
  {
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
      <input type="submit" value="Delete" class="btn btn-default" /> |
      @Html.ActionLink("Back to List", "Index")
    </div>
  }
</div>

MVCMovie/Views/Movies/Details.cshtml
@model MVCMovie.Models.Movie

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Movie</h4>
    <hr />
    <dl class="data-list">
        <dt class="data-list__terms">
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd class="data-list__description">
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt class="data-list__terms">
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>

        <dd class="data-list__description">
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>

        <dt class="data-list__terms">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>

        <dd class="data-list__description">
            @Html.DisplayFor(model => model.Genre)
        </dd>

        <dt class="data-list__terms">
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd class="data-list__description">
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt class="data-list__terms">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd class="data-list__description">
            @Html.DisplayFor(model => model.Rating)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVCMovie/Views/Movies/Edit.cshtml
@model MVCMovie.Models.Movie

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

  <div className="edit-moive__react-anchor" data-movies="@HttpUtility.HtmlEncode(Html.Action("GetMovieListJson", "Movies"))"></div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCMovie/Views/Movies/Index.cshtml
@model IEnumerable<MVCMovie.Models.Movie>

@{
    ViewBag.Title = "Index";
}

@Html.AntiForgeryToken()
<div class="movie-index__react-anchor" data-movies="@HttpUtility.HtmlEncode(Html.Action("GetMovieListJson", "Movies"))"></div>

MVCMovie/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Movie App</title>
    @Styles.Render("/assets/dist/bloc.min.css")

</head>
<body>
  @Html.Partial("_navbar")

  <div class="container body-content">
    @RenderBody()

    <footer class="footer">
      <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
  </div>

  @Scripts.Render("~/bundles/jquery")
  @Scripts.Render("~/bundles/modernizr")
  @RenderSection("scripts", required: false)
  <script src='/assets/dist/bloc.min.js'></script>
</body>
</html>

MVCMovie/Views/Shared/_navbar.cshtml
<div class="navbar">
  <div class="container">
    <div class="navbar__logo">
      @Html.ActionLink("Movie App", "Index", "Movies", "Movies", new { @class = "navbar__logo__h3" })
    </div>
    <div class="navbar__container">
      <ul class="navbar__container__ul">
        <li class="navbar__container__ul__li">@Html.ActionLink("Home", "Index", "Home", new { }, new { @class = "navbar__container__ul__li__a" })</li>
        <li class="navbar__container__ul__li">@Html.ActionLink("About", "About", "Home", new { }, new { @class = "navbar__container__ul__li__a" })</li>
        <li class="navbar__container__ul__li">@Html.ActionLink("Contact", "Contact", "Home", new { }, new { @class = "navbar__container__ul__li__a" })</li>
        <li class="navbar__container__ul__li">@Html.ActionLink("Movies", "Index", "Movies", new { }, new { @class = "navbar__container__ul__li__a" })</li>
      </ul>
    </div>
  </div>
</div>